services:
  - type: web
    name: nitter
    env: docker
    plan: free
    region: oregon
    branch: master
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        value: nitter-redis
      - key: REDIS_PORT
        value: 6379
    dependsOn:
      - name: nitter-redis

  - type: redis
    name: nitter-redis
    plan: free
